@startuml

class Object <<Entity>> {
    - Node_cid  // 原子事件的节点ID
    - Resource_id //资源id
    - Timestamp //本机创建时间戳
    - Last_id //因果关系事件id(上一个关联事件id) 为空代表没有因果关系
    - Operations //自定义操作集
    - Properties //自定义属性信息
}

class Link <<Entity>> {
    - Name  // string link的名字
    - Hash //Multihash 数据的加密哈希值
    - Size //数据大小
    - Created_time   //
    - Updated_time //
}

' p2pdb_log --> p2pdb_log_event
@enduml
