@startuml
class p2pdb_log <<Entity>> {
    - created_time   //
    - updated_time //
}

class p2pdb_log_event <<Entity>> {
    - envent_id  // 原子事件ID
    - resource_id //资源id
    - timestamp //本机创建时间戳
    - cid //节点cid
    - last_id //因果关系事件id(上一个关联事件id) 为空代表没有因果关系
    - operations //自定义操作集
    - properties //自定义属性信息
    - created_time   //
    - updated_time //
}

p2pdb_log --> p2pdb_log_event
@enduml
